# Documentation: http://docs.travis-ci.com/user/languages/julia
language: julia
notifications:
  email: false
julia:
  - 1.6
  - nightly
os:
  - linux
#   - osx
arch:
  - x64
cache:
  directories:
    - ~/.julia/artifacts
before_install:
  - sudo apt-get update
#          - pip3 -m install -U matplotlib
  - sudo apt-get install python3-matplotlib
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  include:
#     - stage: test
#       julia:
#         - 1.5
#         - nightly
#       os: linux
#       dist: focal
#       before_install:
#         - sudo apt-get update
# #          - pip3 -m install -U matplotlib
#         - sudo apt-get install python3-matplotlib
    - stage: Documentation
      julia: 1.6
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       name: "HTML"
      script: |
          julia --project=docs -e '
          using Pkg
          Pkg.develop(PackageSpec(path=pwd()))
          Pkg.instantiate()
          using Documenter: doctest
          using FlxQTL
          doctest(FlxQTL)
          include("docs/make.jl")'
      after_success: skip
after_success:
  - |
    julia -e '
      using Pkg
      Pkg.add("Coverage")
      using Coverage
      Codecov.submit(process_folder())'

# before_install:
#   - julia -e 'ENV["PYTHON"]=""; Pkg.add("Conda"); using Conda;  Conda.add("python==3.9.0"); Conda.add("matplotlib==3.3.2"); Conda.add("basemap"); Pkg.add("PyCall"); Pkg.build("PyCall"); Pkg.add("PyPlot");'
